/*
 * Session Tester - The Exploratory Testing Tool, a tool to help manage exploratory testing sessions, prime testing ideas and record test results.
 *
 * Copyright (C) 2008 Jonathan Kohl, Aaron West
 *
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package sessiontester.client;

import javax.swing.JOptionPane;

/**
 * Used to initiate a testing session.
 */
public class NewSessionDialog extends javax.swing.JDialog {

    private ClientController controller;

    /** Creates new form NewSessionDialog */
    public NewSessionDialog(java.awt.Frame parent, boolean modal, ClientController controller) {
        super(parent, modal);
        this.controller = controller;
        initComponents();
        jTesterTextField.requestFocus();
        jStartButton.setEnabled(false);
        setLocationRelativeTo(parent);
    }

    public void reset() {
        jTesterTextField.setText("");
        jMissionTextField.setText("");
        jSessionLengthComboBox.setSelectedIndex(0);
        jSessionEndComboBox.setSelectedIndex(0);
        jMissionReminderIntervalComboBox.setSelectedIndex(0);
        jMissionReminderCheckBox.setSelected(false);
        jSessionEndCheckBox.setSelected(false);
        jTesterTextField.grabFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jTesterTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jMissionTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSessionLengthComboBox = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMissionReminderCheckBox = new javax.swing.JCheckBox();
        jMissionReminderIntervalComboBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSessionEndCheckBox = new javax.swing.JCheckBox();
        jSessionEndComboBox = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jStartButton = new javax.swing.JButton();
        jCancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("sessiontester/client/resources/NewSessionDialog"); // NOI18N
        setTitle(bundle.getString("title.text")); // NOI18N
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NewSessionDialog.class);
        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        jTesterTextField.setName("jTesterTextField"); // NOI18N
        jTesterTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTesterTextFieldKeyReleased(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jMissionTextField.setName("jMissionTextField"); // NOI18N
        jMissionTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jMissionTextFieldKeyReleased(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jSessionLengthComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "15", "20", "25", "30", "35", "40", "45", "50", "55", "60", "65", "70", "75", "80", "85", "90", "95", "100", "105", "110", "115", "120" }));
        jSessionLengthComboBox.setName("jSessionLengthComboBox"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jMissionReminderCheckBox.setText(resourceMap.getString("jMissionReminderCheckBox.text")); // NOI18N
        jMissionReminderCheckBox.setName("jMissionReminderCheckBox"); // NOI18N

        jMissionReminderIntervalComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jMissionReminderIntervalComboBox.setName("jMissionReminderIntervalComboBox"); // NOI18N

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jSessionEndCheckBox.setText(resourceMap.getString("jSessionEndCheckBox.text")); // NOI18N
        jSessionEndCheckBox.setName("jSessionEndCheckBox"); // NOI18N

        jSessionEndComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15" }));
        jSessionEndComboBox.setName("jSessionEndComboBox"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        jStartButton.setText(bundle.getString("jStartButton.Text")); // NOI18N
        jStartButton.setName("jStartButton"); // NOI18N
        jStartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStartButtonActionPerformed(evt);
            }
        });

        jCancelButton.setText(bundle.getString("jCancelButton.Text")); // NOI18N
        jCancelButton.setName("jCancelButton"); // NOI18N
        jCancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelButtonActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel11)
                    .add(jLabel7)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jTesterTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel5))
                    .add(layout.createSequentialGroup()
                        .add(jMissionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel9))
                    .add(layout.createSequentialGroup()
                        .add(jSessionLengthComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 66, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(layout.createSequentialGroup()
                            .add(jMissionReminderCheckBox)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jMissionReminderIntervalComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                            .add(jSessionEndCheckBox)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jSessionEndComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jLabel8))))
                .add(24, 24, 24))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jStartButton)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 304, Short.MAX_VALUE)
                .add(jCancelButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTesterTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel11)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jMissionTextField, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabel9))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jSessionLengthComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jMissionReminderCheckBox)
                    .add(jMissionReminderIntervalComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jSessionEndCheckBox)
                    .add(jSessionEndComboBox, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8))
                .add(33, 33, 33)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCancelButton)
                    .add(jStartButton))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jStartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStartButtonActionPerformed
        controller.startNewSessionDialogCompleted();
    }//GEN-LAST:event_jStartButtonActionPerformed

    private void jCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelButtonActionPerformed
        controller.startNewSessionDialogCancelled();
    }//GEN-LAST:event_jCancelButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.startNewSessionDialogCancelled();
    }//GEN-LAST:event_formWindowClosing

    private void jTesterTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTesterTextFieldKeyReleased
        updateStartButton();
    }//GEN-LAST:event_jTesterTextFieldKeyReleased

    private void jMissionTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMissionTextFieldKeyReleased
        updateStartButton();
    }//GEN-LAST:event_jMissionTextFieldKeyReleased

    private void updateStartButton() {
        this.jLabel5.setVisible(this.jTesterTextField.getText().length() == 0);
        this.jLabel9.setVisible(this.jMissionTextField.getText().length() == 0);

        boolean b1 = this.jTesterTextField.getText().length() > 0;
        boolean b2 = this.jMissionTextField.getText().length() > 0;
        this.jStartButton.setEnabled(b1 && b2);
    }

    public String getMissionText() {
        return jMissionTextField.getText();
    }

    public String getTesterText() {
        return jTesterTextField.getText();
    }

    public int getSessionLength() {
        return Integer.parseInt(jSessionLengthComboBox.getSelectedItem().toString());
    }

    public int getMissionReminderInterval() {
        return Integer.parseInt(jMissionReminderIntervalComboBox.getSelectedItem().toString());
    }

    public int getSessionEndReminderInterval() {
        return Integer.parseInt(jSessionEndComboBox.getSelectedItem().toString());
    }

    public boolean isMissionReminderChecked() {
        return (jMissionReminderCheckBox.getSelectedObjects() != null);
    }

    public boolean isSessionEndReminderChecked() {
        return (jSessionEndCheckBox.getSelectedObjects() != null);
    }

    public void focusOnTesterField() {
        jTesterTextField.grabFocus();
    }

    public void showError(String title, String message) {
        JOptionPane.showMessageDialog(this, title, message, JOptionPane.ERROR_MESSAGE);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JCheckBox jMissionReminderCheckBox;
    private javax.swing.JComboBox jMissionReminderIntervalComboBox;
    private javax.swing.JTextField jMissionTextField;
    private javax.swing.JCheckBox jSessionEndCheckBox;
    private javax.swing.JComboBox jSessionEndComboBox;
    private javax.swing.JComboBox jSessionLengthComboBox;
    private javax.swing.JButton jStartButton;
    private javax.swing.JTextField jTesterTextField;
    // End of variables declaration//GEN-END:variables
}
